# This workflow will build a Java project with Gradle

name: Build

on: [push, pull_request, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/build
